name: Deploy Beta

on:
  workflow_run:
    workflows: ['CI']
    branches:
      - main
    types:
      - completed
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-beta:
    name: Deploy to Beta
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: beta
      stack_prefix: Beta
      bucket_name: brwyatt-me-beta-site-assets
      domain: beta.brwyatt.me
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN_BETA }}
