name: Promote to Production

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for deployment'
        required: false
        default: 'Production deployment release'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    name: Deploy to Production
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: production
      stack_prefix: Prod
      bucket_name: brwyatt-me-prod-site-assets
      domain: brwyatt.me
    secrets:
      aws_role_arn: ${{ secrets.AWS_ROLE_ARN_PROD }}
